### ISSUE TITLE
(Light Mode) Top bar artwork shows white patches next to transparent bar

### ISSUE THREAD

**Issue by KillerParticles** [yazninja/itheme-plus-plus#5]
So a bit hard to explain, but the space next to the artwork to the left is not transparent but instead white, this means it doesn't seamlessly transition and so looks off.
![image](https://user-images.githubusercontent.com/93286201/170050446-f74d1547-75a8-46d6-b8a2-df40ee4025d7.png)

**Comment by yazninja** [comment]
ill just label it, pls move
