### ISSUE TITLE
(Light Mode) Cannot see highlight effect on mouseover on sidebar

### ISSUE THREAD

**Issue by KillerParticles** [yazninja/itheme-plus-plus#6]
So a bit hard to explain, but on dark mode as you see here, when you hover the mouse over the tabs here, such as the songs tab, it highlights it; 
![image](https://user-images.githubusercontent.com/93286201/170051187-6df44ab9-26ab-48f1-a9cb-8511f8281f33.png)

But heres how it looks on light mode, you can barely see it;
![image](https://user-images.githubusercontent.com/93286201/170051320-3c644cc5-6b75-414b-82ae-3ff8eafd294e.png)

**Comment by yazninja** [comment]
pls once again, move to itheme
