### ISSUE TITLE
Top bar is still clickable in Music Videos

### ISSUE THREAD

**Issue by KillerParticles** [yazninja/itheme-plus-plus#8]
When playing a Music Video, the top area of the video where the top bar is can still be clicked, this means you can click anywhere up there and it will close out the music video and go to whatever you clicked on, you can try it by playing a music video and hovering your mouse cursor over the top area, you will notice it will show you can click on it, which will close the music video. It should not be able to be clicked.

**Comment by yazninja** [comment]
Can you check if this is only present in iTheme or also in normal Cider, might be a change there

**Comment by yazninja** [comment]
Cider issue, can add this there
